name: CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            #- run: sudo apt-get install redis-server
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11 
             # Downloads a copy of the code in your repository before running CI tests
            - name: Check out repository code
              uses: actions/checkout@v2

              # Performs a clean installation of all dependencies in the `package.json` file
              # For more information, see https://docs.npmjs.com/cli/ci.html
            - name: Install dependencies
              run: npm ci

            - name: Connect to Redis
                # Runs a script that creates a Redis client, populates
                # the client with data, and retrieves data
              run: node client.js
                # Environment variable used by the `client.js` script to create
                # a new Redis client.
              env:
                  # The hostname used to communicate with the Redis service container
                  REDIS_HOST: localhost
                  # The default Redis port
                  REDIS_PORT: 6379 
            -  run: mvn clean install 
            -  run: cd redis
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                  args:
                      build -c redis
              
              env: 
                  JAVA_HOME: /usr/lib/jvm/default-jvm
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
